# NumPy Array 1D, 2D and 3D

Import NumPy library

In [1]:
import numpy as np
print(np.__version__)

1.19.5


Creating Numpy Array using np.array() --> Direct initialization

In [2]:
# creating 1D array
arr_1D = np.array([1,2,3,4])
print(np.shape(arr_1D)) 					            # Output: (4,)
print(arr_1D.shape) 					                # Output: (4,)
print("np.shape returns : " + str(type(arr_1D.shape))) 	# Output: np.shape returns : <class 'tuple'>
print(arr_1D.dtype) 					                # Output: int32
print(arr_1D.ndim) 					                    # Output: 1

(4,)
(4,)
np.shape returns : <class 'tuple'>
int32
1


In [3]:
# creating 2D array
arr_2D = np.array([[1,2,3,4],[5,6,7,8],[9,11,20,21]])
print(np.shape(arr_2D)) 					            # Output: (3,4)
print(arr_2D.shape) 					                # Output: (3,4)
print("np.shape returns : " + str(type(arr_2D.shape))) 	# Output: np.shape returns : <class 'tuple'>
print(arr_2D.dtype) 					                # Output: int32
print(arr_2D.ndim) 					                    # Output: 2

(3, 4)
(3, 4)
np.shape returns : <class 'tuple'>
int32
2


In [4]:
# creating 2D array
arr_3D = np.array([[[1,2,3,4],[7,6,5,2],[8,9,3,4]],[[1,2,3,4],[7,6,5,2],[8,9,3,4]],[[1,2,3,4],[7,6,5,2],[8,9,3,4]]])
print(np.shape(arr_3D)) 					            # Output: (3,2,3)
print(arr_3D.shape) 					                # Output: (3,2,3)
print("np.shape returns : " + str(type(arr_3D.shape))) 	# Output: np.shape returns : <class 'tuple'>
print(arr_3D.dtype) 					                # Output: int32
print(arr_3D.ndim) 					                    # Output: 3


(3, 3, 4)
(3, 3, 4)
np.shape returns : <class 'tuple'>
int32
3


Place holders

In [8]:
# np.zeros
# creating arrays with zero
arr_1D_zeros = np.zeros(2)          #1D array
arr_2D_zeros = np.zeros((2,2))      #2D array
arr_3D_zeros = np.zeros((2,2,2))    #3D array

print(arr_1D_zeros)
print(arr_2D_zeros)
print(arr_3D_zeros)

In [34]:
# np.ones
# creating arrays with one
arr_1D_ones = np.ones(3)          #1D array
arr_2D_ones = np.ones((3,3))      #2D array
arr_3D_ones = np.ones((3,3,3))    #3D array

print(arr_1D_ones)
print(arr_2D_ones)
print(arr_3D_ones)

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [22]:
# np.empty
# creating arrays with small values
arr_1D_empty = np.empty(3)          #1D array
arr_2D_empty = np.empty([3,3])      #2D array
arr_3D_empty = np.empty([3,3,3])    #3D array

print(arr_1D_empty)
print(arr_2D_empty)
print(arr_3D_empty)

[1.23881674e-311 0.00000000e+000 8.54515833e+194]
[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 7.94457559e-321]
 [3.98449938e+252 8.03700728e-095 4.71280061e+257]]
[[[1.23881895e-311 8.44852254e-322 0.00000000e+000]
  [0.00000000e+000 1.89146896e-307 1.16096346e-028]
  [1.04857803e-142 1.16467185e-028 7.11936158e-071]]

 [[1.96087669e+243 7.49232703e+247 6.03835653e+151]
  [1.09936966e+248 6.03835653e+151 9.15002793e+242]
  [3.94658447e+180 1.96087669e+243 6.97283728e+228]]

 [[1.96087669e+243 1.01601965e+160 9.07216338e+223]
  [9.15002793e+242 1.14572577e+243 3.74502571e+233]
  [5.48947967e-096 8.47613321e+136 2.56765542e-312]]]


In [27]:
# np.eye
# creating arrays with 1 at the diagonal
arr_2D_diag = np.eye(3)

print(arr_2D_diag)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
# np.full
# creating arrays with desired values
arr_1D_full =  np.full((3), 2)
arr_2D_full =  np.full((3, 3), 2)
arr_3D_full =  np.full((3, 3, 3), 2)

print(arr_1D_full)
print(arr_2D_full)
print(arr_3D_full)

[2 2 2]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[[2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]]]


In [33]:
# np.random.rand
# creating arrays with random values
arr_1D_rand =  np.random.rand(3)
arr_2D_rand =  np.random.rand(3, 3)
arr_3D_rand =  np.random.rand(3, 3, 3)

print(arr_1D_rand)
print(arr_2D_rand)
print(arr_3D_rand)

[0.46778157 0.26073354 0.50163708]
[[0.23938871 0.70741353 0.95204069]
 [0.69144634 0.18587188 0.36965513]
 [0.89701735 0.314832   0.9149256 ]]
[[[0.7494059  0.39518458 0.42687203]
  [0.64411215 0.87069035 0.54712567]
  [0.39680668 0.85417618 0.98511222]]

 [[0.07890133 0.8666866  0.11207338]
  [0.31013186 0.80367788 0.59382019]
  [0.66087765 0.00533347 0.79779062]]

 [[0.86469633 0.66253041 0.28973875]
  [0.4780897  0.96006832 0.99752648]
  [0.80870082 0.89800666 0.91258147]]]
