# Numpy array operations

import library

In [1]:
import numpy as np

create array

In [70]:
# 1-D array
A = np.array([1,3,2])
B = np.array([3,5,7])

# 2-D array
C = np.array([[1,6,3],[8,9,5],[7,2,4]])
D = np.array([1,3,4,8,9,6])

# operations

In [14]:
#adding element
print(A)
print(A+2)
print(A*2)
print(A-2)
print(A/2)

#adding array
print(A+B)
print(A*B)
print(A-B)
print(A/B)

[1 3 2]
[3 5 4]
[2 6 4]
[-1  1  0]
[0.5 1.5 1. ]
[4 8 9]
[ 3 15 14]
[-2 -2 -5]
[0.33333333 0.6        0.28571429]


In [24]:
# mathematical functions
print(A)
print(np.exp(A))            # exponential (complex and real)
print(np.sin(A))            # sine
print(np.std(A))            # standard deviation
print(np.radians(A))        # degrees to radians
print(np.degrees(A))        # radians to degrees
print(np.var(A))            # variance of array
print(np.sum(A))            # sum over axis 1
print(np.abs(A))            # return absolute values

[1 3 2]
[ 2.71828183 20.08553692  7.3890561 ]
[0.84147098 0.14112001 0.90929743]
0.816496580927726
[0.01745329 0.05235988 0.03490659]
[ 57.29577951 171.88733854 114.59155903]
0.6666666666666666
6
[1 3 2]


In [39]:
print(A)
print(B)
print(np.power(A,B))        # a to the power b
print(np.arctan2(A, B))     # arctan(a/b)
print(np.dot(A, B))         # inner product: a_mi b_in
print(np.outer(A, B))       # outer product
print(np.add(A,B))          # addition
print(np.lcm(A,B))          # LCM
print(np.gcd(A,B))          # GCD
print(np.mod(A,B))          # mod
print(np.fft.fft(A))        # complex fourier transform of a

[1 3 2]
[3 5 7]
[  1 243 128]
[0.32175055 0.5404195  0.27829966]
32
[[ 3  5  7]
 [ 9 15 21]
 [ 6 10 14]]
[4 8 9]
[ 3 15 14]
[1 1 1]
[1 3 2]
[ 6. +0.j        -1.5-0.8660254j -1.5+0.8660254j]


Indexing

In [41]:
# 1D array
print(B[0])
print(B[2])
print(B[1:])
print(B[-2])
print(B[0:1])
print(B[0:2:2]) 

3

In [69]:
# 2D array
print(C[0,0])
print(C[2,0])
print(C[1,1:])
print(C[1:,1:])
print(C[0:-1,:-1])
print(C[0:2,-1]) 

1
7
[9 5]
[[9 5]
 [2 4]]
[[1 6]
 [8 9]]
[3 5]


reshape

In [80]:
print(D.reshape(3, 2))
print(D.reshape(2, 1, 3))
print(C.reshape(1,9))

[[1 3]
 [4 8]
 [9 6]]
[[[1 3 4]]

 [[8 9 6]]]
[[1 6 3 8 9 5 7 2 4]]


join

In [87]:
print(np.concatenate((A, B)))
print(np.stack((A, B)))
print(np.hstack((A, B)))
print(np.vstack((A, B)))
print(np.dstack((A, B)))

[1 3 2 3 5 7]
[[1 3 2]
 [3 5 7]]
[1 3 2 3 5 7]
[[1 3 2]
 [3 5 7]]
[[[1 3]
  [3 5]
  [2 7]]]


split

In [93]:
print(np.array_split((D),3))
print(np.array_split((C),3))
print(np.hsplit((D),3))
print(np.vsplit((C),3))

[array([1, 3]), array([4, 8]), array([9, 6])]
[array([[1, 6, 3]]), array([[8, 9, 5]]), array([[7, 2, 4]])]
[array([1, 3]), array([4, 8]), array([9, 6])]
[array([[1, 6, 3]]), array([[8, 9, 5]]), array([[7, 2, 4]])]


sorting

In [97]:
print(np.where(D == 4))
print(np.where(D%2 == 0))
print(np.searchsorted(D, 4))

(array([2], dtype=int64),)
(array([2, 3, 5], dtype=int64),)
2


Save and Load Data

In [98]:
np.save('save_data',D)

In [99]:
E = np.load('save_data.npy')
print(E)

[1 3 4 8 9 6]
